# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\radiobutton.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QDialog


class Ui_Dialog(QDialog):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 295)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.radioButton_python = QtWidgets.QRadioButton(Dialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_python.setFont(font)
        self.radioButton_python.setObjectName("radioButton_python")

        self.radioButton_python.toggled.connect(self.radio_button)

        self.verticalLayout.addWidget(self.radioButton_python)
        self.radioButton_java = QtWidgets.QRadioButton(Dialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_java.setFont(font)
        self.radioButton_java.setObjectName("radioButton_java")

        self.radioButton_java.toggled.connect(self.radio_button)

        self.verticalLayout.addWidget(self.radioButton_java)
        self.radioButton_c = QtWidgets.QRadioButton(Dialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_c.setFont(font)
        self.radioButton_c.setObjectName("radioButton_c")

        self.radioButton_c.toggled.connect(self.radio_button)

        self.verticalLayout.addWidget(self.radioButton_c)
        self.label_result = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_result.setFont(font)
        self.label_result.setText("")
        self.label_result.setObjectName("label_result")
        self.verticalLayout.addWidget(self.label_result)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def radio_button(self):
        radio_btn = self.sender()
        if radio_btn.isChecked():
            self.label_result.setText("you choose : {}".format(radio_btn.text()))

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "choose programming language:"))
        self.radioButton_python.setText(_translate("Dialog", "python"))
        self.radioButton_java.setText(_translate("Dialog", "java"))
        self.radioButton_c.setText(_translate("Dialog", "c++"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
